### ISSUE TITLE
[BUG] Unknown filter error when running kibot

### ISSUE THREAD

**Issue by neilenns** [INTI-CMNB/KiBot#221]
**Describe the bug**
When generating my output files in github I'm getting the following error:

```ERROR:In section ``rotated` (kibom)`: Unknown filter `fix_rotation` used for `pre_transform` (kibot - error.py:40)```

This same workflow was fine on 2022-07-01. I haven't made any changes to my actions, I just moved a footprint to the back of the board in this latest design revision.

**To Reproduce**

Kibot scripts: https://github.com/neilenns/CJ4-Electrical-Panel/tree/main/.kibot. The script running is `includes\JLCPCB-2layer.kibot.yaml`.

**Expected behavior**
No error

**Additional context**

I checked recent code changes and it looks like there was a [merge an hour ago related to filters](https://github.com/INTI-CMNB/KiBot/commit/9ce18ae39be4c2274ee2883d6dba0ed869ae0928). Maybe that broke something?

**Comment by neilenns** [comment]
The GitHub action uses `INTI-CMNB/KiBot@v1_k6`.

**Comment by set-soft** [comment]
Hi @neilenns !
First of all: switch to `v2_k6` for production, `v1_k6` is old and uses the development images.
Now about the filter issue: I'll check it, but the commit you mention could be the problem because you are using the development image.

**Comment by set-soft** [comment]
Confirmed, is related to the commit, the problem is that this check now is done before the filter is actually applied.

**Comment by neilenns** [comment]
I'm running with v2_k6 now, we'll see if that fixes it.

What's the best way for me to stay up to date on what the latest/correct action tags and docker images (for local development) are? I have the same issue in Docker where I'm using `FROM setsoft/kicad_auto:dev_k6`

**Comment by neilenns** [comment]
GitHub action update worked: https://github.com/neilenns/CJ4-Electrical-Panel/releases/tag/v1.1.1

**Comment by neilenns** [comment]
How do I know when those change though? And why would updates to the code break tagged prior images? I would expect (hope) that a tagged prior image is also attached to a specific release of the code so there's no chance of something breaking unless I explicitly roll to a later image tag.

Otherwise things like today happen: my production automation just randomly fails :(

**Comment by set-soft** [comment]
GitHub actions have this problem, I suffered it myself using actions from other users. The mechanism is really easy to use, but you can get some glitches. 

The problem was with a very old tag that was used when we started to experiment with KiCad 5.99, the documentation clearly explains which tag is the one to use with KiCad 6. This problem can still happen after a release. 

If you need a more reliable mechanism switch to use the docker images and select the tag you want.

And if you need 100% reproducibility: create a custom docker image.

Is a trade off between easy of use and consistent results. The development images are currently passing 460 tests for KiCad 5 and KiCad 6 (almost 1000 tests) before creating the development images. But they break something from time to time. Using the stable images hitting a glitch is really rare.

I think that currently you'll hit a bug or limitation more often when using a stable release, this is because KiBot is evolving fast.

In the future I could create some stable images and frozen GitHub actions.
