### ISSUE TITLE
[BUG] text variables in symbols are not resolved in the BOM output

### ISSUE THREAD

**Issue by cdwilson** [INTI-CMNB/KiBot#247]
I use schematic symbols for the schematic & PCB part numbers so that they are included in the assembly BOM. 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/14631/184296512-bca77f1d-73f2-48c4-bf2a-670e035576fa.png">

In KiCad, these symbols are using text variables to set the field values:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/14631/184296614-9a18cb43-6c4b-4388-ac6c-17344544ef8f.png">

In KiBot, I tried to use the `set_text_variables` preflight to set the text variables, but they do not resolve in the BOM output:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/14631/184296717-b3c4aa77-cef6-49c4-bc67-1300180cd1f9.png">

However, they do resolve in the exported schematic PDF:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/14631/184296770-ff913572-648a-4a7c-b4de-7f7826c74d1c.png">

**To Reproduce**

```txt
  set_text_variables:
    - name: SCHEMATIC_PART_NUMBER
      text: "FCD-000036"
    - name: PCB_PART_NUMBER
      text: "FCD-000037"
```

**Expected behavior**
I would expect that the text variables are resolved in the BOM outputs.

**Environment (please complete the following information):**
Where are you running KiBot:
- Using a docker image? `dev_k6`

**Comment by set-soft** [comment]
Hi @cdwilson !
Now should work for the internal BoM.
Note that I didn't check iBoM, KiBoM, KiCost, etc. because this is something that the external tool should solve. But I implemented the rename as a filter, so you can always choose to apply the variables expansion using a filter or variant, and you can choose when the expansion is done, you just need to insert the filter in the filter chain. I know this could sound annoying, but is flexible.
