### ISSUE TITLE
[BUG] Preflights never get run in Makefile builds

### ISSUE THREAD

**Issue by rhalkyard** [INTI-CMNB/KiBot#405]
**Describe the bug**
I want to use KiBot's `-m` option to integrate PCB output into a larger Makefile-based project, but because KiBot's generated makefiles invoke `kibot` with `-s all`, preflights never get run. This means that in Makefile workflows, DRC/ERC checks (if enabled) are not run, and text variables never get set.

**To Reproduce**

* Create a Kicad project and create a text variable
* Generate a quickstart kibot.yaml with `kibot --quick-start --dry`
* Add a `set_text_variables` preflight for one of the project variables (and ensure that `restore_project` is not set anywhere):
```yaml
globals:
  restore_project: false
preflight:
  set_text_variables:
    - name: VARIABLE
      text: hello, world
```
* Generate a makefile with `kibot -m Makefile`

The preflights do not run at Makefile generation time (this can be confirmed by looking at the `.kicad_pro` file to see that the variable has not been changed), but the Makefile explicitly prevents them from running at build time. This means that preflights never get run in a Makefile-based workflow.

Running `kibot <some-target>` outside of the makefile *does* still work as expected, causing the variable to be changed to the value in the preflight.

**Expected behavior**
Preflights are run for Makefile builds.

**Environment (please complete the following information):**
- Ubuntu 20.04.6 on Windows 10 with WSL2
- Kibot 1.6.1 installed from [official Debian repo](https://set-soft.github.io/debian/)
- Kicad 7.0.1 installed from [official Kicad 7.0 PPA](https://launchpad.net/~kicad/+archive/ubuntu/kicad-7.0-releases)

**Additional context**
I can see arguments against running preflights in Makefile builds in general - parallelism and multiple targets could cause headaches if not handled safely. But it would be nice to at least have the option to enable preflights (maybe with a warning that makefiles need to have `.NOTPARALLEL` in them, or to be able to run kibot with preflights only and no target. I can work around the issue by invoking kibot with a dummy target in the parent Makefile that generates the KiBot Makefile. But it would be nice if the process were smoother and less surprising :)

**Comment by set-soft** [comment]
Hi @rhalkyard !

You are right about skipping all pre-flights.
Now the makefile will skip only the pre-flights that has its own target.

About the parallelism: in general is a bad idea to run KiBot targets in parallel unless you really know what they do. The regression tests run some stuff in parallel, but a lot of tests are run sequentially because they can collide.

Also a note: KiCad 7.0.1 won't load the global *fp-lib-table*, you'll get errors about missing lib for all standard KiCad components. This is a known bug, with an available patch. I created Debian package that includes the patch, but is for Debian stable.
