### ISSUE TITLE
[HOW] Using different fonts

### ISSUE THREAD

**Issue by Informaticore** [INTI-CMNB/KiBot#413]
**What do you want to achieve?**
I am using a custom font on my PCB and this font does not exist in the images, when I try to run the kibot.
```
kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            ibom.html octopart.csv schematic.pdf schematic.svg board_top.pdf board_bottom.pdf
```

**Do you have some configuration file (.kibot.yaml) that you are using?**
The workflow can be found here: https://github.com/open-thngs/so-dimm-esp32-programmer/actions/runs/4605069923/workflow

Is there an easy way to install the font in that image? I tried to download it using wgat and curl but both do not exist, is there any other way to achieve this?

**Comment by set-soft** [comment]
Hi @Informaticore !

This is a good question. Lamentably the KiCad developers implemented it in a very weak way. Is really strange because various are seasoned developers. Anybody with some years working with computers already knows that using custom fonts is asking from problems. This is why mature file formats, like PDF, supports embedding the fonts. In fact the IEEE paper validator checks if you embedded all the fonts you used, otherwise the paper is just rejected.

KiCad format is broken because it doesn't support embedding your fonts. So you have to workaround this. I plan to add functionality on KiBot to help to workaround this flaw in the near future, but right now you must choose:

1. Avoid the problem in the first place. Don't use external fonts, this is asking for problems. Many manufacturers currently support KiCad files to take a look at your PCB, not just the gerbers, this is because KiCad is free. Assuming they'll have your fonts, and that they match with your copy of the font, is a really bad idea. Same goes for sharing your project on internet, or even with your friends.
2. Install the fonts in the "machine" where you run KiBot. This what you tried, but failed ;-)

Ok, assuming you really want to go for option 2 lets see if we can find an *easy* way.

1. You must switch to the **full** docker images, you won't have *curl* otherwise. So start changing `ghcr.io/inti-cmnb/kicad7_auto:1.6.1` by `ghcr.io/inti-cmnb/kicad7_auto_full:dev`. Here I'm also recommending to switch to development code, this is so you can test any new commit to help using fonts.
2. Accoring to Debian wiki you must [do it](https://wiki.debian.org/Fonts#:~:text=Install%20a%20font%20manually%20by,fonts%20(user%2Dspecific).)
3. What is the URL to download the font? So I can check if I can make it work.

**Comment by set-soft** [comment]
Looking at your workflow I see you are using the "Archivo SemiBold" font from Omnibus-type.
Installing it on Linux and starting KiCad I get:

![image](https://user-images.githubusercontent.com/22823627/229811792-cfb43fb2-a8ed-421e-8e13-d5dabb74014b.png)

So KiCad can't figure out the font is there and generates a misleading warning.

**Comment by Informaticore** [comment]
I tried it now like this:

```
docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    container:
      image: ghcr.io/inti-cmnb/kicad7_auto_full:dev
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: |
          curl -o Archivo.zip https://fonts.google.com/download?family=Archivo
          unzip Archivo.zip
          cp static/Archivo/Archivo-SemiBold.ttf /usr/local/share/fonts
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            ibom.html octopart.csv schematic.pdf schematic.svg board_top.pdf board_bottom.pdf
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_docs
          if-no-files-found: error
          path: |
            ${{env.dir}}/docs/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
```

So I download the font, unzip it and copy it into `/usr/local/share/fonts` which is supposed to be the place where to put fonts for all users. But it can still not find the font and errors with the dialiog. Do you know where to place the font? Or maybe what I am doing wrong?

**Comment by Informaticore** [comment]
I forgot to add to refresh the cache 
```
fc-cache -v
fc-list
```

The font is now available but it shows the error
`"Font 'Archivo SemiBold' not found; substituting 'Archivo:SemiBold'."` 
and returns. So the naming is now different

**Comment by set-soft** [comment]
> I forgot to add to refresh the cache

Using the current development code you can just add the font to *kibot_resources/fonts* in your repo. It will be automagically installed and the cache refreshed. A regression test is doing it so it works for at least one case.

> The font is now available but it shows the error `"Font 'Archivo SemiBold' not found; substituting 'Archivo:SemiBold'."` and returns. So the naming is now different

This is a KiCad flaw. If you list the fonts you'll see the name is "Archivo SemiBold" as stated in the PCB file. Which output is catching this message?

**Comment by Informaticore** [comment]
>  Which output is catching this message?

Check this run at the end:
https://github.com/open-thngs/so-dimm-esp32-programmer/actions/runs/4616157491/jobs/8160831741

I will give your approach a try tomorrow

**Comment by Informaticore** [comment]
I tried it with the image `ghcr.io/inti-cmnb/kicad7_auto_full:dev` is that the correct dev version? I placed the font in the project root _kibot_resources/fonts_ folder but it could not find it during the build.

**Comment by set-soft** [comment]
> > Which output is catching this message?
> 
> Check this run at the end: https://github.com/open-thngs/so-dimm-esp32-programmer/actions/runs/4616157491/jobs/8160831741
> 
> I will give your approach a try tomorrow

Even when KiAuto needs some adjusts to be cleaver and skip this dialog, why are you using the deprecated print mechanism? Is slow and prone to errors, just use `pcb_print` instead of `pdf_pcb_print`

**Comment by set-soft** [comment]
> I tried it with the image `ghcr.io/inti-cmnb/kicad7_auto_full:dev` is that the correct dev version? I placed the font in the project root _kibot_resources/fonts_ folder but it could not find it during the build.

This is not true. Your workflow says:

```
19:07:14: Warning: Font 'Archivo SemiBold' not found; substituting 'Archivo:SemiBold'.`
```

Which we already discussed is KiCad flaw, the font is there. Just switch to `pcb_print`.
I'll add support for the dialog in the next hour or days.

**Comment by set-soft** [comment]
@Informaticore did you get it working?

**Comment by Informaticore** [comment]
Hey! Sorry I did not got back - yes it is working now. I am running the dev version and placed the font in the folder you mentioned. Now only the my render is not working which I am not sure how to fix. Should I open a new issue for that? I am not sure what the issue is.

Getting this error (but it is not related to the font)

```
ERROR:PcbDraw error: Cannot locate resource /usr/share/pcbdraw/styles/set-black-cu.json; explored paths:
- /usr/share/kibot/pcbdraw
- /github/home/.local/share/pcbdraw
- /usr/share/pcbdraw (kibot - out_pcbdraw.py:500)
```

**Comment by set-soft** [comment]
Hi @Informaticore !

Open a separated issue. 

This file should be installed in */usr/share/kibot/pcbdraw/styles/set-black-cu.json*

Include a small KiBot config that generates it. This sound strange because the regression tests are using `style: set-red-enig` without problems
