### ISSUE TITLE
Explicitly add type to the outputs help

### ISSUE THREAD

**Issue by oliv3r** [INTI-CMNB/KiBot#548]
When looking at the latest readthedocs documentation, the 'types' field is left as an empty string:
![image](https://github.com/INTI-CMNB/KiBot/assets/1245341/7b8b43ec-78f3-4490-85ed-cfef483c0364)

This is quite annoying when looking at the documentation, especially since the code DOES contain the proper type definition: `-  **type** :index:`: <pair: output - pcb2blender_tools; type>` [string=''] Type of output.`

Yes, the type is also listed at the top of the page, but cognitively, this is not where you look normally.

**Comment by set-soft** [comment]
Hi @oliv3r !

The docs are correct, the default value for *type* is an empty string. And yes, the type is at the top. So there is no bug here. In fact the old docs just skipped the *type* because it was at the top and was quite obvious what it means.

That said: Showing how to fill it doesn't do any harm, so now the docs shows it in a way that resembles the YAML use

**Comment by oliv3r** [comment]
Superb! @set-soft you are amazing :D
