### ISSUE TITLE
GitHub Action does not appear to be published to GitHub Marketplace

### ISSUE THREAD

**Issue by jameswilddev** [INTI-CMNB/KiBot#72]
The documentation indicates that this repository can be installed as a GitHub action step:

![image](https://user-images.githubusercontent.com/3138458/116811040-10ea1e00-ab3f-11eb-9031-3bbab64f0de1.png)

However, I get an error when using this which indicates to me that it is not published as action:

![image](https://user-images.githubusercontent.com/3138458/116811067-337c3700-ab3f-11eb-8bbd-292ab4b6562e.png)

And I can't see it on the marketplace:

![image](https://user-images.githubusercontent.com/3138458/116811045-19daef80-ab3f-11eb-8bc4-616dae875524.png)

Has it been unpublished since the documentation was written?

**Comment by nerdyscout** [comment]
actually it was never published since implemented.
As this feature was never completely tested you might want to use instead [kicad-exports](https://github.com/nerdyscout/kicad-exports) which uses kibot v0.11.0

**Comment by set-soft** [comment]
Hi @jameswilddev and @nerdyscout !

What @nerdyscout says is true, we never finished the integration. This is why it isn't published.

But the problem was different (missleading example). Now I added a useful tag name "v1". Updated the docs and also fixed a detail in the `Dockerfile` (a small detail about `curl` package, now available from backports).

A working example can be found here: https://github.com/INTI-CMNB/kicad-ci-test-spora/tree/test_gh_action
