### ISSUE TITLE
[BUG] Component misalignment in PCB Print

### ISSUE THREAD

**Issue by nguyen-v** [INTI-CMNB/KiBot#725]
Fill as much as you can, remove the rest

**Describe the bug**
Some PCB components and DNP crosses are sometimes misaligned, not sure what the cause is but seems to happen more often with THT components:

**To Reproduce**
```
git clone git@github.com:nguyen-v/kibot_tests.git
cd kibot_tests
git checkout 4baff4313ff1c27bc6ed19d11dfb3790b7325f39
kibot -c kibot_tests.yaml
```

Result is in PCB folder

**Expected behavior**
Components should be correctly aligned

**Screenshots**
Pad not aligned:
![image](https://github.com/user-attachments/assets/44237d84-6e4a-4323-9da1-63403d4d38f1)

DNP cross not aligned:
![image](https://github.com/user-attachments/assets/4352caea-1b46-40ff-9af0-ea24bc97e04f)

**Environment (please complete the following information):**
Where are you running KiBot:
WSL2 on Windows 10, dev branch

**Comment by set-soft** [comment]
Ok, the problem here was about the "center" of rotation.
Most SMD components has its center at the geometric center. But this isn't true for THT components, in many cases with center at pin 1.
Now the rotated cross should be using the correct center.
The pad shift was because rotating a footprint might change its center ... so you must memorize the original center.

**Comment by nguyen-v** [comment]
Thanks for the quick fix!
